name: Publish
run-name: Publish @jaronline/${{ inputs.package }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: The name of the package to release
        required: true
        type: choice
        options:
          - blockenv

jobs:
  PublishPackage:
    name: Publish @jaronline/${{ inputs.package }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Publish to NPM
        working-directory: packages/${{ inputs.package }}
        run: |
          yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
          yarn config set npmPublishRegistry "https://registry.yarnpkg.com"

          # Detect whether the current Yarn version is eligible for publishing with provenance (v4.9.0 or later)
          FLAG=$([ $(node -p "require('semver').gte('$(yarn --version)', '4.9.0')") = true ] && echo '--provenance' || echo '')

          yarn npm publish ${FLAG}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
