name: Publish
run-name: Publish @jaronline/${{ inputs.package }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: The name of the package to release
        required: true
        type: choice
        options:
          - blockenv
      skip-automatic-bump:
        description: Whether to skip the automatic bumping of the package version
        required: false
        default: false
        type: boolean

jobs:
  PublishPackage:
    name: Publish @jaronline/${{ inputs.package }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Create App Token
        uses: actions/create-github-app-token@v2
        id: create-token
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ steps.create-token.outputs.token }}
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Configure Git
        run: |
          git config --local user.email "${GITHUB_EMAIL}"
          git config --local user.name "${GITHUB_USER}"
        env:
          GITHUB_USER: jaronline-ci[bot]
          GITHUB_EMAIL: 228008421+jaronline-ci[bot]@users.noreply.github.com
      - name: Bump Versions and make release
        working-directory: packages/${{ inputs.package }}
        run: |
          if [ "${{ inputs.skip-automatic-bump }}" = "true" ]; then
            yarn bump --skip-automatic-bump
          else
            yarn bump
          fi
        env:
          GITHUB_TOKEN: ${{ steps.create-token.outputs.token }}
      - name: Publish to NPM
        working-directory: packages/${{ inputs.package }}
        run: |
          yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
          yarn config set npmPublishRegistry "https://registry.yarnpkg.com"

          # Detect whether the current Yarn version is eligible for publishing with provenance (v4.9.0 or later)
          FLAG=$([ $(node -p "require('semver').gte('$(yarn --version)', '4.9.0')") = true ] && echo '--provenance' || echo '')

          yarn npm publish ${FLAG}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
